version = 0.1

[default.deploy.parameters]
stack_name = "blogging-site-backend"
resolve_s3 = true
s3_prefix = "blogging-site"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []

# Pass parameter values to the stack
parameter_overrides = "SupabaseUrl=\"https://mtslsqeaubbubqzryoxx.supabase.co\" SupabaseAnonKey=\"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im10c2xzcWVhdWJidWJxenJ5b3h4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwNDM2MzQsImV4cCI6MjA2MjYxOTYzNH0.abAIJzNhJwOC3X3EsKrYXrOEhNEFVWB62nInI_u1MdY\" SupabaseServiceRoleKey=\"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im10c2xzcWVhdWJidWJxenJ5b3h4Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0NzA0MzYzNCwiZXhwIjoyMDYyNjE5NjM0fQ.3eWzWDQ5h8NjE_y6-_SDhngP1prCSXv0yQuFPjLt-1o\" DatabaseUrl=\"postgresql+asyncpg://postgres.mtslsqeaubbubqzryoxx:L1osfMZ46nCb0Y7O@aws-0-ap-south-1.pooler.supabase.com:6543/postgres\" JwtSecretKey=\"Dxv2jHT6hM3W7gi+bzcmkm8ZDN85eG1dIdDHVxivQrOOOg0iPGMGPFvVPz9Y5UHwb1q355CKYAG8Y7CK1s9Qqw==\" SupabaseStorageBucket=\"blog-media\""
profile = "ashwath"

[default.deploy.environment]
SUPABASE_URL = "https://mtslsqeaubbubqzryoxx.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im10c2xzcWVhdWJidWJxenJ5b3h4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwNDM2MzQsImV4cCI6MjA2MjYxOTYzNH0.abAIJzNhJwOC3X3EsKrYXrOEhNEFVWB62nInI_u1MdY"
SUPABASE_SERVICE_ROLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im10c2xzcWVhdWJidWJxenJ5b3h4Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0NzA0MzYzNCwiZXhwIjoyMDYyNjE5NjM0fQ.3eWzWDQ5h8NjE_y6-_SDhngP1prCSXv0yQuFPjLt-1o"
DATABASE_URL = "postgresql+asyncpg://postgres:L1osfMZ46nCb0Y7O@db.mtslsqeaubbubqzryoxx.supabase.co:5432/postgres"
JWT_SECRET_KEY = "Dxv2jHT6hM3W7gi+bzcmkm8ZDN85eG1dIdDHVxivQrOOOg0iPGMGPFvVPz9Y5UHwb1q355CKYAG8Y7CK1s9Qqw=="
SUPABASE_STORAGE_BUCKET = "blog-media"
