"""init migrations

Revision ID: da5cf2a783c1
Revises: 
Create Date: 2025-06-10 14:35:00.688767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da5cf2a783c1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_followers',
    sa.Column('follower_id', sa.UUID(), nullable=False),
    sa.Column('following_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('follower_id != following_id', name='no_self_follow_check'),
    sa.ForeignKeyConstraint(['follower_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['following_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('follower_id', 'following_id', name='user_followers_pkey')
    )
    op.create_index('idx_follower_id', 'user_followers', ['follower_id'], unique=False)
    op.create_index('idx_following_id', 'user_followers', ['following_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_following_id', table_name='user_followers')
    op.drop_index('idx_follower_id', table_name='user_followers')
    op.drop_table('user_followers')
    # ### end Alembic commands ###
